### ISSUE TITLE
баг в readme

### ISSUE THREAD

**Issue by talgautb** [karmazzin/eloquentjavascript_ru#15]
Так и должно быть ?
![Alt text](https://monosnap.com/file/yNMCCpZczYzkcgIqYtgUWRzcsnT9KK.png)

там нереальное кол-во `br`

**Comment by karmazzin** [comment]
Это единственное решение, что пришло мне в голову, чтобы сделать в pdf разрыв страницы перед введением.

**Comment by talgautb** [comment]
@karmazzin посмотри [тут](http://forums.apricitysoftware.com/t/include-pdf-pagebreak-instructions-in-markdown/152)
пишут, что работает, у меня что-то не получается)

**Comment by karmazzin** [comment]
@talgautb, не выходит каменный цветок, пусть остается так.
