### ISSUE TITLE
Можно ли пересобрать книгу?

### ISSUE THREAD

**Issue by denysdovhan** [karmazzin/eloquentjavascript_ru#16]
В pdf размер шрифта в 18pt, насколько я понимаю. Могу ли я пересобрать книгу под себя с размером шрифта, например, 14pt?
Хочу книгу напечатать, но перед этим уменьшить шрифт в целях экономии бумаги.

**Comment by karmazzin** [comment]
@denysdovhan, у сервиса gitbook под капотом работает вот это - https://github.com/GitbookIO/gitbook, правда именно в pdf у меня собрать не вышло с ее помощью, только epub и html. Попробуйте. 

(issue закрою, будет что сказать - открывай вновь)
