### ISSUE TITLE
сущности в html

### ISSUE THREAD

**Issue by Anisotropic** [karmazzin/eloquentjavascript_ru#25]
стр 236  - сущности превратились в символы:

"Открывающая скобка (она же знак «меньше») записывается как < («less
than», «меньше, чем»), закрывающая — > (“greater that”, «больше, чем»). В
HTML амперсанд &, за которым идёт слово и точка с запятой, зовётся
сущностью и заменяется символом, который кодируется этой
последовательностью.
Это похоже на обратные слэши, используемые в строках JavaScript. Из-за
специального значения амперсанда его самого в текст можно включать в
виде &. В атрибуте, заключаемом в двойные кавычки, символ кавычек
записывается как ".

**Comment by karmazzin** [comment]
#28 
Поправил
