### ISSUE TITLE
PDF и скроллбары

### ISSUE THREAD

**Issue by MityaResh** [karmazzin/eloquentjavascript_ru#26]
![38db478675](https://cloud.githubusercontent.com/assets/11774509/6968774/e1b5245e-d971-11e4-823e-43d4d1150c19.jpg)
Возможна ли переверстка PDF варианта с переносом строк в коде? (на скриншоте страница 224 pdf версии)

**Comment by karmazzin** [comment]
@ru-pacman, готово)
