### ISSUE TITLE
Версия для слабовидящих под kindle

### ISSUE THREAD

**Issue by cikoriicabachkov** [karmazzin/eloquentjavascript_ru#33]
Привет!
На kindle цвет шрифта в книге серый, читать тяжело. Люди страдают. Можно ли сделать версию с чёрным, как ночь, шрифтом?

**Comment by karmazzin** [comment]
Привет, @cikoriicabachkov! 
Не без мучений, но подключил-таки плагин, позволяющий изменять стили. В веб-версии подхватилось, проверь, как в mobi, и отпишись, пожалуйста.

**Comment by cikoriicabachkov** [comment]
В mobi всё отлично! Большущее спасибо от всех страждущих!

**Comment by karmazzin** [comment]
Ну все, доброе дело сделал, день не зря прожил. Удачи!
